In [1]:
import torch as tc

# repeat

In [8]:
a = tc.tensor([1, 2])
a.shape
a

torch.Size([2])

tensor([1, 2])

In [9]:
b = a.repeat(2, 3)
b.shape
b

torch.Size([2, 6])

tensor([[1, 2, 1, 2, 1, 2],
        [1, 2, 1, 2, 1, 2]])

In [10]:
a = tc.tensor([[1, 2], [3, 4]])
a.shape
a

torch.Size([2, 2])

tensor([[1, 2],
        [3, 4]])

In [11]:
b = a.repeat(2, 3)
b.shape
b

torch.Size([4, 6])

tensor([[1, 2, 1, 2, 1, 2],
        [3, 4, 3, 4, 3, 4],
        [1, 2, 1, 2, 1, 2],
        [3, 4, 3, 4, 3, 4]])

In [12]:
a = tc.tensor([1, 2])
a.shape
a

torch.Size([2])

tensor([1, 2])

In [13]:
b = a.repeat(2, 1)
b.shape
b

torch.Size([2, 2])

tensor([[1, 2],
        [1, 2]])